### PR TITLE
Ensure binary() for kinit input args

### PR DESCRIPTION
**Pull request by zmstone**

### CODE REVIEW

**Review by ElMaxo — APPROVED** [review]

**Comment by zmstone** [comment]
@ElMaxo merge ?

**Comment by ElMaxo** [comment]
Ready

**Comment by zmstone** [comment]
I have done the tests yesterday.
All good (except that it's not quite easy to get kerberos working).
awesome work @ElMaxo

**Comment by ElMaxo** [comment]
@zmstone Thanks for kind words. To be honest, i don't like kerberos, all dirty work with kerberos setup at cluster was made by our dev ops. Also, they use Apache Ambari, as far as i know it can do it process simplier

**Comment by zmstone** [comment]
Apache Ambrai.
I'll check that out.
thanks for the info.

**Pull request merged**
