### PR TITLE
Add example to make it easy to test brod_gssapi

### PR DESCRIPTION
**Pull request by kjellwinblad**
* **This is based on PR https://github.com/kafka4beam/brod_gssapi/pull/5 which should be merged first**
* Currently, `brod_gssapi` fails to connect to the Kafka instance in this example. This should be fixed before merge.

This PR adds a `docker-compose` example that sets up Kerberos and Kafka (with SASL GSSAPI Kerberos authentication). The script `example/test_send_receive.sh` can be used to test that the Kafka instance works once it has been started with the `example/up` script.

The example also includes a small Erlang application (`example/brod_client`) that uses `brod_gssapi` to send and receive a message to/from the Kafka instance. This can be started with `docker-compose up brod_client` (from the example dir) once the Kafka instance has been started with the `up` script. Unfortunately,  this does not currently work. When looking at the Kafka logs `docker-compose logs kafka` it seems like authentication is successful but that Kafka receives a package that it does not expect afterwards which causes it to close the connection. This could be related to the issue reported here https://github.com/kafka4beam/brod/issues/383.

### CODE REVIEW

**Comment by kjellwinblad** [comment]
I created an issue with error logs and a detailed description of how to reproduce the problem with `example/brod_client` here https://github.com/kafka4beam/brod_gssapi/issues/7.

**Comment by starbelly** [comment]
@kjellwinblad 

1. The docker compose setup is great :) 

2. I can at least clearly see that after we sent the initial token successfully, we perform our first client step, but we get back an empty token (`{sasl_continue, <<>>}`), we then try to send this to kafka, and kafka gets angry as we sent it a "null" value.  

Will need to dig some more....

@kjellwinblad  The problem is the version of `brod` your pulling in from git. Possibly sending an empty token is a legit case (documented  by Vikas in a previous iteration). If I simply pull in the latest version from hex, auth completes successfully. So seemingly a bug after 2253f675c6c2fb0527366a43546eb45d5be086ff (v3.16.2) was introduced.

Edit: 

Seems to be related to just pulling in via git deps, which suggests a build issue. If pull in brod via git in rebar.config at `2253f675c6c2fb0527366a43546eb45d5be086ff` it fails. Once again, pulling it in via hex works. 

Edit: 

Hopefully this is my final edit :) Issue is the `rebar.lock`  in brod has kafka_protcol locked at 4.0.1, there were encoder bugs fixed after that release, thus 4.0.2 and 4.0.3 will work. If you modify the rebar.config to this : 


```
{deps, [{brod_gssapi, {path, "../../"}},
        {brod, {git, "https://github.com/kafka4beam/brod.git", {ref, "18ca1e1627bceed279ac83b9e091519b37c9faa4"}}},
        {kafka_protocol, {git, "https://github.com/kafka4beam/kafka_protocol.git", {ref,
        "9ee00f2efa97df23c13d12a48196bed11e183f41"}}}
        ]}.
```

It'll work (4.0.2). Probably should do a PR to brod to bump to 4.0.2? Maybe also use hex deps vs git deps, though it would be good to have two profiles one that pulls in main/master from git and the other from hex (i.e, latest stable).

**Comment by kjellwinblad** [comment]
Thank you @starbelly! I will make a PR to brod and see what I can do about the two profiles.

**Comment by kjellwinblad** [comment]
@starbelly after fixing the version according to your suggestion [6ea28d0](https://github.com/kafka4beam/brod_gssapi/pull/6/commits/6ea28d08a4f6c5db6a8409069fc6c7522f519717) (merged into the prod repo and new version of brod released) the brod client seem connects which is a big improvement. Unfortunately, I'm having trouble sending a message to a topic. I have created a topic mytest (this is done by the `example/test_send_receive.sh`) and then I execute the code in brod_client/src/example.erl (`docker-compose up brod_client` after the `./up` script has executed). Everything goes well until hitting this line:

```
{ok, FirstOffset} = brod:produce_sync_offset(client1, Topic, Partition, <<"FistKey">>, <<"FirstValue">>),
```

Which cause a crash with the following info:

```
brod_client  | Args: []
brod_client  | {going_to_connect,[{"kafka.kerberos-demo.local",9093}]}
brod_client  | =ERROR REPORT==== 7-Jun-2022::13:33:56.530814 ===
brod_client  | ** Generic server <0.122.0> terminating
brod_client  | ** Last message in was retry
brod_client  | ** When Server state == {state,<0.114.0>,<<"mytest">>,0,undefined,undefined,
brod_client  |                                {buf,512,1,1048576,3,0,0,
brod_client  |                                     {fun brod_producer:do_send_fun/4,
brod_client  |                                      {<<"mytest">>,0,-1,10000,no_compression}},
brod_client  |                                     1,0,
brod_client  |                                     {[],[]},
brod_client  |                                     {[],[]},
brod_client  |                                     []},
brod_client  |                                500,#Ref<0.1571305242.899678209.231971>,
brod_client  |                                undefined,
brod_client  |                                {default,0}}
brod_client  | ** Reason for termination ==
brod_client  | ** {{reached_max_retries,no_leader_connection},
brod_client  |     [{brod_producer_buffer,rebuffer_or_crash,3,
brod_client  |                            [{file,"/opt/brod_gssapi/example/brod_client/_build/default/lib/brod/src/brod_producer_buffer.erl"},
brod_client  |                             {line,312}]},
brod_client  |      {brod_producer_buffer,do_send,4,
brod_client  |                            [{file,"/opt/brod_gssapi/example/brod_client/_build/default/lib/brod/src/brod_producer_buffer.erl"},
brod_client  |                             {line,296}]},
brod_client  |      {brod_producer,maybe_produce,1,
brod_client  |                     [{file,"/opt/brod_gssapi/example/brod_client/_build/default/lib/brod/src/brod_producer.erl"},
brod_client  |                      {line,525}]},
brod_client  |      {brod_producer,handle_info,2,
brod_client  |                     [{file,"/opt/brod_gssapi/example/brod_client/_build/default/lib/brod/src/brod_producer.erl"},
brod_client  |                      {line,325}]},
brod_client  |      {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,695}]},
brod_client  |      {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,771}]},
brod_client  |      {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
brod_client  |
brod_client  | {"init terminating in do_boot",{{badmatch,{error,{producer_down,{reached_max_retries,no_leader_connection}}}},[{example,main,1,[{file,"/opt/brod_gssapi/example/brod_client/src/example.erl"},{line,23}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,685}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
brod_client  | init terminating in do_boot ({{badmatch,{error,{producer_down,{_}}}},[{example,main,1,[{_},{_}]},{erl_eval,do_apply,6,[{_},{_}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})
brod_client  |
brod_client  | Crash dump is being written to: erl_crash.dump...done
```

When the topic does not exists I get another error saying that the topic does not exists which indicate that the authentication is successful. Maybe the most interesting info from the error reason is `{reached_max_retries,no_leader_connection}`. Do you have any idea what that means? The Kafka logs contains the following info:

```
kafka        | [2022-06-07 13:33:47,042] DEBUG Finding range of cleanable offsets for log=__consumer_offsets-2. Last clean offset=None now=1654608827040 => firstDirtyOffset=0 firstUncleanableOffset=0 activeSegment.baseOffset=0 (kafka.log.LogCleanerManager$)
kafka        | [2022-06-07 13:33:54,981] DEBUG Accepted connection from /172.21.0.6:45738 on /172.21.0.4:9093 and assigned it to processor 0, sendBufferSize [actual|requested]: [102400|102400] recvBufferSize [actual|requested]: [102400|102400] (kafka.network.Acceptor)
kafka        | [2022-06-07 13:33:54,981] DEBUG Processor 0 listening to new connection from /172.21.0.6:45738 (kafka.network.Processor)
kafka        | [2022-06-07 13:33:54,981] DEBUG connections.max.reauth.ms for mechanism=GSSAPI: 0 (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
kafka        | [2022-06-07 13:33:54,985] DEBUG Set SASL server state to HANDSHAKE_OR_VERSIONS_REQUEST during authentication (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
kafka        | [2022-06-07 13:33:54,985] DEBUG Handling Kafka request API_VERSIONS during authentication (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
kafka        | [2022-06-07 13:33:54,986] DEBUG Set SASL server state to HANDSHAKE_REQUEST during authentication (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
kafka        | [2022-06-07 13:33:54,993] DEBUG Handling Kafka request SASL_HANDSHAKE during authentication (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
kafka        | [2022-06-07 13:33:54,993] DEBUG Using SASL mechanism 'GSSAPI' provided by client (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
kafka        | [2022-06-07 13:33:54,993] DEBUG Creating SaslServer for kafka/kafka.kerberos-demo.local@TEST.CONFLUENT.IO with mechanism GSSAPI (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
kafka        | Found KeyTab /var/lib/secret/kafka.key for kafka/kafka.kerberos-demo.local@TEST.CONFLUENT.IO
kafka        | Found ticket for kafka/kafka.kerberos-demo.local@TEST.CONFLUENT.IO to go to krbtgt/TEST.CONFLUENT.IO@TEST.CONFLUENT.IO expiring on Wed Jun 08 13:24:17 UTC 2022
kafka        | [2022-06-07 13:33:54,994] DEBUG Set SASL server state to AUTHENTICATE during authentication (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
kafka        | Entered Krb5Context.acceptSecContext with state=STATE_NEW
kafka        | Looking for keys for: kafka/kafka.kerberos-demo.local@TEST.CONFLUENT.IO
kafka        | Added key: 17version: 1
kafka        | Added key: 18version: 1
kafka        | >>> EType: sun.security.krb5.internal.crypto.Aes256CtsHmacSha1EType
kafka        | Using builtin default etypes for permitted_enctypes
kafka        | default etypes for permitted_enctypes: 18 17 20 19 16 23.
kafka        | >>> EType: sun.security.krb5.internal.crypto.Aes256CtsHmacSha1EType
kafka        | MemoryCache: add 1654608834/991269/6FE6EB9CA805ABE231ABA303D2B98CAF9D207BEB5EB3855606AFDEEBA8CE201A/rig@TEST.CONFLUENT.IO to rig@TEST.CONFLUENT.IO|kafka/kafka.kerberos-demo.local@TEST.CONFLUENT.IO
kafka        | >>> KrbApReq: authenticate succeed.
kafka        | Krb5Context setting peerSeqNumber to: 128213701
kafka        | >>> EType: sun.security.krb5.internal.crypto.Aes256CtsHmacSha1EType
kafka        | Krb5Context setting mySeqNumber to: 636518880
kafka        | Krb5Context.wrap: data=[01 01 00 00 ]
kafka        | Krb5Context.wrap: token=[05 04 01 ff 00 0c 00 00 00 00 00 00 25 f0 81 e0 01 01 00 00 c6 9f c2 7a 48 c8 81 a5 3e 44 8c 92 ]
kafka        | Krb5Context.unwrap: token=[05 04 00 ff 00 0c 00 00 00 00 00 00 07 a4 62 c5 01 00 00 00 72 69 67 40 54 45 53 54 2e 43 4f 4e 46 4c 55 45 4e 54 2e 49 4f 53 60 12 59 09 8a 96 1c 75 61 df d9 ]
kafka        | Krb5Context.unwrap: data=[01 00 00 00 72 69 67 40 54 45 53 54 2e 43 4f 4e 46 4c 55 45 4e 54 2e 49 4f ]
kafka        | [2022-06-07 13:33:54,996] INFO Successfully authenticated client: authenticationID=rig@TEST.CONFLUENT.IO; authorizationID=rig@TEST.CONFLUENT.IO. (org.apache.kafka.common.security.authenticator.SaslServerCallbackHandler)
kafka        | [2022-06-07 13:33:54,996] DEBUG Authentication complete; session max lifetime from broker config=0 ms, no credential expiration; no session expiration, sending 0 ms to client (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
kafka        | [2022-06-07 13:33:54,996] DEBUG Set SASL server state to COMPLETE during authentication (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
kafka        | [2022-06-07 13:33:54,996] DEBUG [SocketServer listenerType=ZK_BROKER, nodeId=0] Successfully authenticated with /172.21.0.6 (org.apache.kafka.common.network.Selector)
kafka        | [2022-06-07 13:33:55,005] DEBUG Accepted connection from /172.21.0.6:45750 on /172.21.0.4:9093 and assigned it to processor 1, sendBufferSize [actual|requested]: [102400|102400] recvBufferSize [actual|requested]: [102400|102400] (kafka.network.Acceptor)
kafka        | [2022-06-07 13:33:55,005] DEBUG Processor 1 listening to new connection from /172.21.0.6:45750 (kafka.network.Processor)
kafka        | [2022-06-07 13:33:55,005] DEBUG connections.max.reauth.ms for mechanism=GSSAPI: 0 (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
kafka        | [2022-06-07 13:33:55,005] DEBUG Set SASL server state to HANDSHAKE_OR_VERSIONS_REQUEST during authentication (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
kafka        | [2022-06-07 13:33:55,005] DEBUG Handling Kafka request API_VERSIONS during authentication (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
kafka        | [2022-06-07 13:33:55,005] DEBUG Set SASL server state to HANDSHAKE_REQUEST during authentication (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
kafka        | [2022-06-07 13:33:55,007] DEBUG [SocketServer listenerType=ZK_BROKER, nodeId=0] Connection with /172.21.0.6 disconnected (org.apache.kafka.common.network.Selector)
kafka        | java.io.EOFException
kafka        | 	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:97)
kafka        | 	at org.apache.kafka.common.security.authenticator.SaslServerAuthenticator.authenticate(SaslServerAuthenticator.java:257)
kafka        | 	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:181)
kafka        | 	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:543)
kafka        | 	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
kafka        | 	at kafka.network.Processor.poll(SocketServer.scala:989)
kafka        | 	at kafka.network.Processor.run(SocketServer.scala:892)
kafka        | 	at java.base/java.lang.Thread.run(Thread.java:829)
kafka        | [2022-06-07 13:33:56,019] DEBUG Accepted connection from /172.21.0.6:45762 on /172.21.0.4:9093 and assigned it to processor 2, sendBufferSize [actual|requested]: [102400|102400] recvBufferSize [actual|requested]: [102400|102400] (kafka.network.Acceptor)
kafka        | [2022-06-07 13:33:56,019] DEBUG Processor 2 listening to new connection from /172.21.0.6:45762 (kafka.network.Processor)
kafka        | [2022-06-07 13:33:56,019] DEBUG connections.max.reauth.ms for mechanism=GSSAPI: 0 (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
kafka        | [2022-06-07 13:33:56,019] DEBUG Set SASL server state to HANDSHAKE_OR_VERSIONS_REQUEST during authentication (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
kafka        | [2022-06-07 13:33:56,019] DEBUG Handling Kafka request API_VERSIONS during authentication (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
kafka        | [2022-06-07 13:33:56,020] DEBUG Set SASL server state to HANDSHAKE_REQUEST during authentication (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
kafka        | [2022-06-07 13:33:56,028] DEBUG [SocketServer listenerType=ZK_BROKER, nodeId=0] Connection with /172.21.0.6 disconnected (org.apache.kafka.common.network.Selector)
kafka        | java.io.EOFException
kafka        | 	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:97)
kafka        | 	at org.apache.kafka.common.security.authenticator.SaslServerAuthenticator.authenticate(SaslServerAuthenticator.java:257)
kafka        | 	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:181)
kafka        | 	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:543)
kafka        | 	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
kafka        | 	at kafka.network.Processor.poll(SocketServer.scala:989)
kafka        | 	at kafka.network.Processor.run(SocketServer.scala:892)
kafka        | 	at java.base/java.lang.Thread.run(Thread.java:829)
kafka        | [2022-06-07 13:33:56,552] DEBUG [SocketServer listenerType=ZK_BROKER, nodeId=0] Connection with /172.21.0.6 disconnected (org.apache.kafka.common.network.Selector)
kafka        | java.io.EOFException
kafka        | 	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:97)
kafka        | 	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
kafka        | 	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
kafka        | 	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
kafka        | 	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
kafka        | 	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
kafka        | 	at kafka.network.Processor.poll(SocketServer.scala:989)
kafka        | 	at kafka.network.Processor.run(SocketServer.scala:892)
kafka        | 	at java.base/java.lang.Thread.run(Thread.java:829)
kafka        | [2022-06-07 13:34:02,043] DEBUG Finding range of cleanable offsets for log=__consumer_offsets-13. Last clean offset=None now=1654608842043 => firstDirtyOffset=0 firstUncleanableOffset=0 activeSegment.baseOffset=0 (kafka.log.LogCleanerManager$)
```

@starbelly @zmstone do you have any idea what is happening here? It seems to me that the brod_producer is disconnecting when Kafka is expecting something else. What could be the reason for that?

**Comment by zmstone** [comment]
had a look together with @kjellwinblad 
it was due to a bad advitersed.listener config.

**Comment by kjellwinblad** [comment]
As mentioned by @zmstone, the issue was fixed by changing the advitersed.listener config ([6dae865](https://github.com/kafka4beam/brod_gssapi/pull/6/commits/6dae865a5433cce6c63a2782134a3f922934020e)). Apparently, this was an issue for brod but the not for Kafka's command line clients https://github.com/kafka4beam/brod_gssapi/blob/6dae865a5433cce6c63a2782134a3f922934020e/example/test_send_receive.sh. Thanks @zmstone!

**Comment by zmstone** [comment]
It's an issue for any client which needs to (re)connect the advertised endpoints.
Maybe Kafka's command line client re-uses the bootstrap endpoint for produce/consume.

**Comment by kjellwinblad** [comment]
@starbelly @zmstone I will add commits to this PR to fix the github action that @zmstone added and also add a github action that will run the GSSAPI (Kerberos) Kafka setup to check that brod_gssapi can connect to a real system. So you do not need to fix the GitHub action in any other PR.

**Comment by kjellwinblad** [comment]
@starbelly:
> Maybe also use hex deps vs git deps, though it would be good to have two profiles one that pulls in main/master from git and the other from hex (i.e, latest stable).

I have added github actions for running with the latest version of brod, the master branch, and version 3.16.3. Now, it is also easy to test with a custom version of brod. See 27b4e60.

**Comment by starbelly** [comment]
> @starbelly:
> 
> > Maybe also use hex deps vs git deps, though it would be good to have two profiles one that pulls in main/master from git and the other from hex (i.e, latest stable).
> 
> I have added github actions for running with the latest version of brod, the master branch, and version 3.16.3. Now, it is also easy to test with a custom version of brod. See [27b4e60](https://github.com/kafka4beam/brod_gssapi/commit/27b4e606564aaf38cfc68d04bc1d58da2a649a91).

Cool. I can remove the one I have in current PR I have open, or you can deal with conflicts. Let me know. As a side note to that PR. I'll push up docs tonight and then we can merge it. Wanted to get the tests cleaned up, but can do a follow up PR for that, rather not be blocking.

**Review by zmstone — APPROVED** [review]
great! maybe rebase to tidy up the commits.

**Comment by kjellwinblad** [comment]
@starbelly:
> Cool. I can remove the one I have in current PR I have open, or you can deal with conflicts. Let me know.

I think you can keep it. I will deal with the conflicts. But it is up to you.

@zmstone:
> great! maybe rebase to tidy up the commits.

Yes, I will rebase and tidy up the commits after PR https://github.com/kafka4beam/brod_gssapi/pull/5 has been merged.

**Comment by kjellwinblad** [comment]
@starbelly I rebased on your latest changes and now it fails: https://github.com/kafka4beam/brod_gssapi/runs/6809888396?check_suite_focus=true .

Do you have any idea about what the problem might be?

Edit:
The HandshakeVsn that is sent to kpro_req_lib:make at line 130 in brod_gssapi_v1.erl is `gen_tcp`, which does not seem right.

Edit again:

I think I use the wrong callback module in the settings. Will try to change that to see if it will work.

**Comment by kjellwinblad** [comment]
@starbelly: I got it to work after chaning the callback module but I also think I found a bug. See 
477db0e.

* It seems like the parameter for handshake version is placed at the wrong location here https://github.com/kafka4beam/brod_gssapi/commit/477db0e123aed2ebe05ccaa2903d6c2ccc175314#diff-67b0b6e83545a5a13324adb1e254a848d397157cd0ddb483dbd263d34d1c3645L44
* Also, handshake version 0 did not work with the example set up. Do we want handshake version 0 to be the default for old `kafka_protocol` versions (without the new callback function) or is it better to use version 1 (I don't know which one is most common).

**Comment by starbelly** [comment]
> @starbelly: I got it to work after chaning the callback module but I also think I found a bug. See [477db0e](https://github.com/kafka4beam/brod_gssapi/commit/477db0e123aed2ebe05ccaa2903d6c2ccc175314).
> 
>     * It seems like the parameter for handshake version is placed at the wrong location here [477db0e#diff-67b0b6e83545a5a13324adb1e254a848d397157cd0ddb483dbd263d34d1c3645L44](https://github.com/kafka4beam/brod_gssapi/commit/477db0e123aed2ebe05ccaa2903d6c2ccc175314#diff-67b0b6e83545a5a13324adb1e254a848d397157cd0ddb483dbd263d34d1c3645L44)

Indeed :) I'll fix that up, also why I like using maps when number params > 4 (as a guide line). 
> 
>     * Also, handshake version 0 did not work with the example set up. Do we want handshake version 0 to be the default for old `kafka_protocol` versions (without the new callback function) or is it better to use version 1 (I don't know which one is most common).

Maybe we can find some stats on this, the old version goes back to 2015 I believe? If that's right, it's quite old and I would think most have would upgraded since.

**Comment by kjellwinblad** [comment]
> Indeed :) I'll fix that up, also why I like using maps when number params > 4 (as a guide line).

It looks like the placement of the handshake version is still wrong but I can fix that in a commit to this PR.

https://github.com/kafka4beam/brod_gssapi/blob/5f236246860b6c947297de471069c0f1ca2a23db/src/brod_gssapi.erl#L43

**Pull request merged**
